export const ALL_PROJECT_NAME =
  '1INCH,AAVE,AGLD,ALPHA,APE,AXS,BADGER,BAL,BAND,BAT,BICO,BNT,CHZ,COMP,CRO,CRV,CVC,DYDX,ENJ,ENS,GALA,GMT,GODS,GRT,KISHU,KNC,LINK,LOOKS,LPT,LRC,MANA,MASK,MATIC,MKR,PEOPLE,REN,RSR,SAND,SHIB,SLP,SNX,STORJ,SUSHI,THETA,TRB,UMA,UNI,YFI,YGG,ZRX,BLUR,GMX,SWEAT,LDO,OP,MAGIC,WOO,IMX,API3,GFT,ARB,RDNT,PEPE,AIDOGE,WLD,PERP,FLOKI,VRA,FRONT,BIGTIME,RACA,MEME,FLOW,SSV,INJ,AUCTION,MSN,FOXY,BLOCK,ETHFI,BONE,AEVO,RAY,VELO,GPT,T,ACH,OM,STRK,ZETA,DMAIL,LQTY,FXS,NMR,JOE,METIS,ACE,TURBO,CTC,RON,ID,ZENT,GLM,ULTI,ATH,ZRO,CVX,UXLINK'.split(
    ',',
  );

export const ALL_CHANNEL = [
  '15m',
  '1H',
  '4H',
  '1D',
  '2D',
  '3D',
  '5D',
  '1W',
  '1M',
  '3M',
];
